import os

# Generated by scripts/apply_config.py from attdef.yml.
# Edit attdef.yml, then run ./farm apply.

CONFIG = {
    'DEBUG': os.getenv('DEBUG') == '1',
    'TEAMS': {'Team #1': '127.0.0.1'},
    'FLAG_FORMAT': 'FLAG\\{[A-Za-z0-9_]+\\}',

    'SYSTEM_PROTOCOL': 'ctfcup_tcp',
    'SYSTEM_HOST': '5.129.237.176',
    'SYSTEM_PORT': 31337,

    'SUBMIT_FLAG_LIMIT': 100,
    'SUBMIT_PERIOD': 2,
    'FLAG_LIFETIME': 300,
    'SERVER_PASSWORD': os.getenv('SERVER_PASSWORD') or 'change-me',
    'TIMEZONE': 'Europe/Moscow',
}
