#!/usr/bin/env python3
import argparse
import ipaddress
import os
import re
import secrets
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def parse_scalar(value):
    value = value.strip()
    if value == "":
        return ""
    if (value[0], value[-1]) in (("'", "'"), ('"', '"')):
        inner = value[1:-1]
        if value[0] == "'":
            return inner.replace("''", "'")
        return bytes(inner, "utf-8").decode("unicode_escape")
    if value.lower() in ("true", "false"):
        return value.lower() == "true"
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def parse_simple_yaml(path):
    root = {}
    stack = [(-1, root)]
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if indent % 2:
            raise SystemExit(f"{path}:{lineno}: indentation must use 2-space steps")
        item = raw.strip()
        if ":" not in item:
            raise SystemExit(f"{path}:{lineno}: expected key: value")
        key, value = item.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            raise SystemExit(f"{path}:{lineno}: empty key")
        while indent <= stack[-1][0]:
            stack.pop()
        parent = stack[-1][1]
        if value == "":
            node = {}
            parent[key] = node
            stack.append((indent, node))
        else:
            parent[key] = parse_scalar(value)
    return root


def need_map(cfg, key):
    value = cfg.get(key, {})
    if not isinstance(value, dict):
        raise SystemExit(f"{key} must be a map")
    return value


def get_path(cfg, dotted, default=None):
    cur = cfg
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return default
        cur = cur[part]
    return cur


def neo_client_farm_url(cfg):
    neo = need_map(cfg, "neo")
    configured = neo.get("client_farm_url")
    if configured not in (None, ""):
        return str(configured).rstrip("/")
    return f"http://127.0.0.1:{get_path(cfg, 'ports.s4dfarm', 5137)}"


def load_env(path):
    env = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key] = value
    return env


def token_hex(nbytes=16):
    return secrets.token_hex(nbytes)


def env_value(env, key, default):
    return env.get(key) or str(default)


def write_file(path, text, mode=None):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    if mode is not None:
        path.chmod(mode)


def py_value(value):
    return repr(value)


def validate_protocol(name):
    proto_dir = ROOT / "services/S4DFarm/server/app/protocols"
    allowed = sorted(p.stem for p in proto_dir.glob("*.py") if p.stem != "__init__")
    if name not in allowed:
        joined = ", ".join(allowed)
        raise SystemExit(f"unknown checksystem.protocol {name!r}; available: {joined}")


def render_s4d_config(cfg):
    server = need_map(cfg, "server")
    teams = need_map(cfg, "teams")
    flags = need_map(cfg, "flags")
    submitter = need_map(cfg, "submitter")
    checksystem = need_map(cfg, "checksystem")

    protocol = str(checksystem.get("protocol", "ctfcup_tcp"))
    validate_protocol(protocol)

    lines = [
        "import os",
        "",
        "# Generated by scripts/apply_config.py from attdef.yml.",
        "# Edit attdef.yml, then run ./farm apply.",
        "",
        "CONFIG = {",
        "    'DEBUG': os.getenv('DEBUG') == '1',",
        f"    'TEAMS': {py_value(dict(teams))},",
        f"    'FLAG_FORMAT': {py_value(str(flags.get('format', r'FLAG\\{[A-Za-z0-9_]+\\}')))},",
        "",
        f"    'SYSTEM_PROTOCOL': {py_value(protocol)},",
    ]

    mapping = {
        "host": "SYSTEM_HOST",
        "port": "SYSTEM_PORT",
        "url": "SYSTEM_URL",
        "token": "SYSTEM_TOKEN",
        "team_token": "TEAM_TOKEN",
        "validator": "SYSTEM_VALIDATOR",
        "server_key": "SYSTEM_SERVER_KEY",
    }
    for cfg_key, farm_key in mapping.items():
        value = checksystem.get(cfg_key)
        if value not in (None, ""):
            lines.append(f"    {py_value(farm_key)}: {py_value(value)},")

    extra = checksystem.get("extra", {})
    if extra:
        if not isinstance(extra, dict):
            raise SystemExit("checksystem.extra must be a map")
        for key, value in extra.items():
            lines.append(f"    {py_value(str(key))}: {py_value(value)},")

    lines.extend(
        [
            "",
            f"    'SUBMIT_FLAG_LIMIT': {int(submitter.get('flag_limit', 100))},",
            f"    'SUBMIT_PERIOD': {int(submitter.get('period', 2))},",
            f"    'FLAG_LIFETIME': {int(flags.get('lifetime', 300))},",
            "    'SERVER_PASSWORD': os.getenv('SERVER_PASSWORD') or 'change-me',",
            f"    'TIMEZONE': {py_value(str(server.get('timezone', 'Europe/Moscow')))},",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_neo_server_config(cfg):
    neo = need_map(cfg, "neo")
    client_farm_url = neo_client_farm_url(cfg)
    env = {
        "S4DFARM_URL": client_farm_url,
        "S4DFARM_CACHEPROXY": f"http://{get_path(cfg, 'server.public_ip', '127.0.0.1')}:{get_path(cfg, 'ports.cacheproxy', 8888)}",
    }
    extra_env = neo.get("env", {})
    if extra_env:
        if not isinstance(extra_env, dict):
            raise SystemExit("neo.env must be a map")
        env.update({str(k): str(v) for k, v in extra_env.items()})

    env_lines = "\n".join(f"  {k}: {v!r}" for k, v in sorted(env.items()))
    return f"""# Generated by scripts/apply_config.py from attdef.yml.
db_path: "/data/db.db"
redis_url: "redis://neo-redis:6379/0"
base_dir: "/data/exploits"
client_farm_url: "{client_farm_url}"
ping_every: "{neo.get('ping_every', '5s')}"
submit_every: "{neo.get('submit_every', '2s')}"
grpc_auth_key: ""

farm:
  url: "http://s4d-farm:5000"
  password: ""

env:
{env_lines}
"""


def render_neo_client_config(cfg, grpc_key):
    public_ip = get_path(cfg, "server.public_ip", "127.0.0.1")
    grpc_port = get_path(cfg, "ports.neo_grpc", 5005)
    victoria_port = get_path(cfg, "ports.victoria", 8428)
    return f"""# Generated by scripts/apply_config.py from attdef.yml.
host: "{public_ip}:{grpc_port}"
metrics_host: "127.0.0.1:{victoria_port}/api/v1/import/prometheus"
exploit_dir: "exploits"
grpc_auth_key: "{grpc_key}"
verbose: false
"""


def cert_sans(cfg):
    public_name = str(get_path(cfg, "server.public_ip", "127.0.0.1"))
    sans = ["DNS:localhost", "IP:127.0.0.1"]
    try:
        ipaddress.ip_address(public_name)
    except ValueError:
        sans.append(f"DNS:{public_name}")
    else:
        sans.append(f"IP:{public_name}")
    return sorted(dict.fromkeys(sans))


def ensure_tls_certificate(cfg):
    cert_dir = ROOT / "runtime/tls"
    cert = cert_dir / "farm.crt"
    key = cert_dir / "farm.key"
    marker = cert_dir / "farm.san"
    sans = ",".join(cert_sans(cfg))

    if cert.exists() and key.exists() and marker.exists() and marker.read_text().strip() == sans:
        return

    if shutil.which("openssl") is None:
        raise SystemExit("openssl is required to generate runtime/tls self-signed certificate")

    cert_dir.mkdir(parents=True, exist_ok=True)
    public_name = str(get_path(cfg, "server.public_ip", "127.0.0.1"))
    subprocess.run(
        [
            "openssl",
            "req",
            "-x509",
            "-newkey",
            "rsa:2048",
            "-sha256",
            "-nodes",
            "-days",
            "30",
            "-keyout",
            str(key),
            "-out",
            str(cert),
            "-subj",
            f"/CN={public_name}",
            "-addext",
            f"subjectAltName={sans}",
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    key.chmod(0o600)
    cert.chmod(0o644)
    write_file(marker, sans + "\n", 0o644)


def write_env(cfg):
    env_path = ROOT / ".env"
    old = load_env(env_path)

    project = str(cfg.get("project", "vibe_cat_but_sad_farm"))
    server_password = env_value(old, "SERVER_PASSWORD", token_hex(16))
    client_farm_url = neo_client_farm_url(cfg)
    env = {
        "COMPOSE_PROJECT_NAME": project,
        "DEBUG": env_value(old, "DEBUG", 0),
        "S4DFARM_PORT": get_path(cfg, "ports.s4dfarm", 5137),
        "HTTPS_S4DFARM_PORT": get_path(cfg, "ports.https_s4dfarm", 5443),
        "CACHEPROXY_PORT": get_path(cfg, "ports.cacheproxy", 8888),
        "EXTERNAL_REDIS_PORT": get_path(cfg, "ports.external_redis", 6378),
        "NEO_GRPC_PORT": get_path(cfg, "ports.neo_grpc", 5005),
        "NEO_WEBUI_PORT": get_path(cfg, "ports.neo_webui", 8090),
        "HTTPS_NEO_WEBUI_PORT": get_path(cfg, "ports.https_neo_webui", 8443),
        "VICTORIA_PORT": get_path(cfg, "ports.victoria", 8428),
        "NEO_WORKER_JOBS": get_path(cfg, "neo.worker_jobs", 20),
        "SERVER_PASSWORD": server_password,
        "FARM_PASSWORD": server_password,
        "EXTERNAL_REDIS_PASSWORD": env_value(old, "EXTERNAL_REDIS_PASSWORD", token_hex(24)),
        "GRPC_AUTH_KEY": env_value(old, "GRPC_AUTH_KEY", token_hex(32)),
        "WEB_PASSWORD": env_value(old, "WEB_PASSWORD", token_hex(16)),
        "NEO_FARM_URL": "http://s4d-farm:5000",
        "NEO_CLIENT_FARM_URL": client_farm_url,
    }

    lines = [
        "# Generated by scripts/apply_config.py.",
        "# Secrets are preserved on repeated ./farm apply runs.",
    ]
    for key, value in env.items():
        value = str(value).replace("\n", "")
        lines.append(f"{key}={value}")
    write_file(env_path, "\n".join(lines) + "\n", 0o600)
    return env


def patch_prometheus_config():
    path = ROOT / "services/neo/monitoring/cfg/prometheus/config.yml"
    write_file(
        path,
        """scrape_configs:
  - job_name: 'neo_server'
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
      - targets: ['neo-server:3000']

  - job_name: 's4d_farm_api'
    scrape_interval: 10s
    scrape_timeout: 3s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['s4d-front:80']

  - job_name: 's4d_farm_celery'
    scrape_interval: 10s
    scrape_timeout: 3s
    metrics_path: '/celery/metrics'
    static_configs:
      - targets: ['s4d-front:80']
""",
    )


def compile_s4d_config():
    subprocess.run(
        [sys.executable, "-m", "py_compile", str(ROOT / "services/S4DFarm/server/app/config.py")],
        check=True,
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("config", nargs="?", default=str(ROOT / "attdef.yml"))
    args = parser.parse_args()

    cfg_path = Path(args.config)
    if not cfg_path.is_absolute():
        cfg_path = ROOT / cfg_path
    cfg = parse_simple_yaml(cfg_path)
    ensure_tls_certificate(cfg)
    env = write_env(cfg)

    write_file(ROOT / "services/S4DFarm/server/app/config.py", render_s4d_config(cfg))
    write_file(ROOT / "services/neo/configs/server/config.yml", render_neo_server_config(cfg))
    write_file(
        ROOT / "services/neo/client_env/client_config.yml",
        render_neo_client_config(cfg, env["GRPC_AUTH_KEY"]),
        0o600,
    )
    patch_prometheus_config()
    compile_s4d_config()

    print("Config applied.")
    public_ip = get_path(cfg, "server.public_ip", "127.0.0.1")
    print(f"S4DFarm HTTPS: https://{public_ip}:{get_path(cfg, 'ports.https_s4dfarm', 5443)}")
    print(f"Neo Web UI HTTPS: https://{public_ip}:{get_path(cfg, 'ports.https_neo_webui', 8443)}")


if __name__ == "__main__":
    main()
